#!/usr/bin/env python3
"""Build/check the self-contained prototype with installed tools only."""

from __future__ import annotations

import argparse
from html.parser import HTMLParser
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / "prototype" / "workspace.html"
MODEL = ROOT / "prototype" / "model.js"
CONTROLLER = ROOT / "prototype" / "controller.js"
FRAGMENT = ROOT / "prototype" / "dashboard.fragment.html"
DESTINATION = ROOT / "prototype" / "index.html"


class FragmentCheck(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.ids: list[str] = []
        self.references: list[str] = []
        self.scripts: list[str] = []
        self.in_script = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attributes = dict(attrs)
        if attributes.get("id"):
            self.ids.append(attributes["id"])
        if attributes.get("aria-controls"):
            self.references.append(attributes["aria-controls"])
        if tag == "script":
            self.in_script = True
            if attributes.get("src"):
                raise ValueError("The standalone study must not load external scripts.")

    def handle_endtag(self, tag: str) -> None:
        if tag == "script":
            self.in_script = False

    def handle_data(self, data: str) -> None:
        if self.in_script:
            self.scripts.append(data)


def read_fragment() -> tuple[str, str]:
    fragment = TEMPLATE.read_text(encoding="utf-8")
    for marker, source in (("/* BOTAINER_MODEL */", MODEL),
                           ("/* BOTAINER_CONTROLLER */", CONTROLLER)):
        if fragment.count(marker) != 1:
            raise ValueError(f"Expected exactly one template marker: {marker}")
        javascript = source.read_text(encoding="utf-8")
        if "</script" in javascript.lower():
            raise ValueError(f"Script closing tag in {source.name}")
        fragment = fragment.replace(marker, javascript)
    if re.search(r"<!doctype\s|<\s*(?:html|head|body)(?:\s|>)", fragment, re.I):
        raise ValueError("The editable source must be an HTML fragment.")
    if len(fragment.encode("utf-8")) >= 1_000_000:
        raise ValueError("The prototype fragment is unexpectedly large.")
    check = FragmentCheck()
    check.feed(fragment)
    if len(check.ids) != len(set(check.ids)):
        raise ValueError("Duplicate HTML IDs.")
    if any(reference not in check.ids for reference in check.references):
        raise ValueError("A control references a missing target.")
    return fragment, "\n".join(check.scripts)


def document(fragment: str) -> str:
    return """<!doctype html>
<!-- Generated by tools/prototype.py; edit workspace.html, model.js, controller.js. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="referrer" content="no-referrer">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; font-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'">
  <title>Botainer Dashboard — terminal workspace prototype</title>
  <style>
    :root { color-scheme: light dark; }
    html, body.bt-standalone { width: 100%; height: 100%; margin: 0; padding: 0; overflow: hidden; }
    body.bt-standalone { background: light-dark(#fff, #1a1d1c); }
    @media (pointer: fine) { #botainer-study .cursor-interaction { cursor: pointer; } }
  </style>
</head>
<body class="bt-standalone">
""" + fragment + "\n</body>\n</html>\n"


def check_javascript(source: str) -> None:
    node = shutil.which("node")
    if node is None:
        print("Node.js is not installed; JavaScript syntax check skipped. Nothing installed.")
        return
    with tempfile.TemporaryDirectory(prefix="botainer-prototype-") as directory:
        path = Path(directory) / "prototype.js"
        path.write_text(source, encoding="utf-8")
        subprocess.run([node, "--check", str(path)], check=True)
    print("JavaScript syntax checked with the existing Node.js.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without rewriting the preview")
    args = parser.parse_args()
    fragment, javascript = read_fragment()
    rendered = document(fragment)
    if args.check:
        if not FRAGMENT.is_file() or FRAGMENT.read_text(encoding="utf-8") != fragment:
            parser.error("Inline preview is stale; run python3 tools/prototype.py")
        if not DESTINATION.is_file() or DESTINATION.read_text(encoding="utf-8") != rendered:
            parser.error("Standalone preview is stale; run python3 tools/prototype.py")
        check_javascript(javascript)
        print("Prototype structure and generated preview are current.")
    else:
        FRAGMENT.write_text(fragment, encoding="utf-8")
        DESTINATION.write_text(rendered, encoding="utf-8")
        print(DESTINATION.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
